calorie_tracker/urls.py
from django.urls import path, include
import calorie_tracker.views as views

app_name="calorie_tracker"
urlpatterns = [
    path("", views.index, name="index"),
    path("products", views.products, name="products"),
    path("meals", views.meals, name="meals"),
    path("about", views.about, name="about"),
    path("user", views.user, name="user"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register", views.register, name="register")
]

calorie_tracker_project/urls.py
from django.contrib import admin
from django.urls import path, include
from calorie_tracker import urls, views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"userprofiles", views.ProfileViewSet)
router.register(r"foods", views.FoodViewSet)
router.register(r"products", views.ProductViewSet)
router.register(r"ingredients", views.IngredientViewSet)
router.register(r"recipes", views.RecipeViewSet)
router.register(r"meals", views.MealViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
    path('api/', include(router.urls)),
    path("api-auth/", include("rest_framework.urls"))
]

calorie_tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

# For PositiveDecimalField
class PositiveDecimalField(models.DecimalField):
    description = _("Positive decimal number")

    @cached_property
    def validators(self):
        return super().validators + [MinValueValidator(Decimal("0"))]

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    calorie_goal = PositiveDecimalField(max_digits=10, decimal_places=2)

    @property
    def username(self):
        return f"{self.user.username}"

    def __str__(self):
        return f"Profile information for {self.user.username}"

class Food(models.Model):
    name = models.CharField(max_length=64)
    calories = PositiveDecimalField(max_digits=10, decimal_places=2) # kcal/100g
    fats = PositiveDecimalField(max_digits=10, decimal_places=2) # g/100g
    carbs = PositiveDecimalField(max_digits=10, decimal_places=2) # g/100g
    proteins = PositiveDecimalField(max_digits=10, decimal_places=2) # g/100g
    portion_size = PositiveDecimalField(max_digits=10, decimal_places=2) # g
    is_locked = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class Product(Food):
    barcode = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    base_product = models.ForeignKey(Product, related_name="ingredients", on_delete=models.SET_NULL, null=True)
    weight = PositiveDecimalField(max_digits=10, decimal_places=2) # Amount of ingredient used

    def __str__(self):
        return f"{self.weight}g of {self.base_product.name}"

class Recipe(Food):
    ingredients = models.ManyToManyField(Ingredient, related_name="recipies")

    def __str__(self):
        return self.name

class Meal(models.Model):
    MEAL_TIME_CHOICES = [
        (1, "Breakfast"),
        (2, "Second Breakfast"),
        (3, "Lunch"),
        (4, "Dinner"),
        (5, "Supper")
    ]
    date = models.DateField(editable=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="meals")
    food = models.ForeignKey(Food, related_name="meals", on_delete=models.CASCADE, null=True, blank=True)
    weight = PositiveDecimalField(max_digits=10, decimal_places=2) # Weight of the meal
    meal_time = models.IntegerField(choices=MEAL_TIME_CHOICES)

    @property
    def total_calories(self):
        return self.weight * self.food.calories / 100
    
    @property
    def total_fats(self):
        return self.weight * self.food.fats / 100
    
    @property
    def total_carbs(self):
        return self.weight * self.food.carbs / 100
    
    @property
    def total_proteins(self):
        return self.weight * self.food.proteins / 100

    def __str__(self):
        return f"{self.user} on {self.date}"

calorie_tracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .models import Product, Meal, Food
from .serializers import *
from rest_framework import permissions, viewsets, status
from rest_framework.response import Response
from django_filters import rest_framework as filters
from django_filters import DateFilter
from .permissions import IsOwnerOrStaff

class ProductFilter(filters.FilterSet):
    class Meta:
        model = Product
        fields = {
            "name": ["contains", "exact"],
            "barcode": ["contains", "exact"]
        }

class MealFilter(filters.FilterSet):
    date = DateFilter()
    class Meta:
        model = Meal
        fields = ["date"]

class ProfileViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = [IsOwnerOrStaff]

class FoodViewSet(viewsets.ModelViewSet):
    queryset = Food.objects.all()
    serializer_class = FoodSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.DjangoFilterBackend]

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.DjangoFilterBackend]
    filterset_class = ProductFilter

    def destroy(self, request, pk=None):
        obj = self.get_object()
        if obj.is_locked:
            return Response(data={'message': "This product is locked and cannot be deleted"}, status=status.HTTP_403_FORBIDDEN)
        self.perform_destroy(obj)
        return Response(status=status.HTTP_204_NO_CONTENT)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        if request.user.is_staff == False:
            if instance.is_locked:
                return Response(data={'message': "This product is locked and cannot be updated by regular user"}, status=status.HTTP_403_FORBIDDEN)
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        if getattr(instance, '_prefetched_objects_cache', None):
            instance._prefetched_objects_cache = {}

        return Response(status=status.HTTP_200_OK)

class IngredientViewSet(viewsets.ModelViewSet):
    queryset = Ingredient.objects.all()
    serializer_class = IngredientSerializer
    permission_classes = [permissions.IsAuthenticated]

class RecipeViewSet(viewsets.ModelViewSet):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer
    permission_classes = [permissions.IsAuthenticated]

class MealViewSet(viewsets.ModelViewSet):
    queryset = Meal.objects.all()
    serializer_class = MealSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_class = MealFilter
    filter_backends = [filters.DjangoFilterBackend]

    def list(self, request):
        queryset = Meal.objects.filter(user=request.user)
        queryset = self.filter_queryset(queryset)
        
        serializer = MealSerializer(queryset, many=True)
        return Response(serializer.data)
    
    def retrieve(self, request, pk=None):
        queryset = Meal.objects.filter(user=request.user)
        queryset = self.filter_queryset(queryset)
        meal = get_object_or_404(queryset, pk=pk)
        serializer = MealSerializer(meal)
        return Response(serializer.data)
    
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def destroy(self, request, pk=None):
        obj = self.get_object()
        if obj.user != self.request.user:
            return Response(data={'message': "This meal can only be deleted by owner"}, status=status.HTTP_403_FORBIDDEN)
        self.perform_destroy(obj)
        return Response(status=status.HTTP_204_NO_CONTENT)


@login_required
def index(request):
    return redirect(reverse("calorie_tracker:meals"))

def products(request):
    return render(request, "calorie_tracker/products.html")

@login_required
def meals(request):
    return render(request, "calorie_tracker/meals.html")

def about(request):
    return render(request, "calorie_tracker/about.html")

@login_required
def user(request):
    return render(request, "calorie_tracker/user.html", {"user_id":request.user.id})

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user) 
            return redirect(reverse("calorie_tracker:index"))
        else:
            return render(request, "registration/register_user.html", {"form":form})
    return render(request, "registration/register_user.html", {"form":UserCreationForm()})

calorie_tracker/templates/calorie_tracker/about.html
{% extends "calorie_tracker/layout.html" %}
{% load static %}
{% block content %}
<div id="react-content"></div>
<script src="{% static 'calorie_tracker/react/pages/about.js' %}" type="application/javascript"></script>
{% endblock %}

calorie_tracker/templates/calorie_tracker/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'calorie_tracker/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>
    <script src="{% static 'calorie_tracker/sessionData.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="{% static 'calorie_tracker/jquery-3.7.1.min.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
    />
    <link rel="icon" type="image/x-icon" href="{% static 'calorie_tracker/favicon.ico' %}">

    <title>Calorie Tracker</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'calorie_tracker:meals' %}">Calorie Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-contorls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'calorie_tracker:meals' %}">My Meals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'calorie_tracker:products' %}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'calorie_tracker:user' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'calorie_tracker:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <form method="POST" id="logout" action="{% url 'calorie_tracker:logout' %}">
                            {% csrf_token %}
                            <a href="#" class="nav-link" onclick="document.querySelector('#logout').submit();">Log out</a>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container text-center mt-2">
        <div class="row justify-content-center">
            <div id="error-message" class="col-sm-12 col-md-10 col-lg-6">
            </div>
        </div>
        <div class="row justify-content-center">
            <div id="content" class="col-sm-12 col-md-10 col-lg-6">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

<!-- TEMPLATES -->

<template id="search-product-options-template">
    <div class="input-group">
        <input type="text" id="food-search-input" class="form-control" placeholder="Product name">
        <button class="btn btn-outline-secondary" type="button" id="add-product-button">Add</button>
        <button class="btn btn-outline-secondary" type="button" id="scan-barcode-button">Scan</button>
    </div>
</template>

<template id="products-list-template">
    <ul class="list-group list-group-flush">
    </ul>
</template>

<template id="products-list-item-template">
    <button class="list-group-item" id="product">
        <h6 id="product-name">Product</h6><small class="text-body-secondary" id="product-calories">Calories</small>
    </button>
</template>

<template id="date-select-template">
    <div class="container">
        <div class="row my-2">
            <div class="col">
                <input type="date" class="form-control" id="date-selector">
            </div>
        </div>
    </div>
</template>

<template id="mealtimes-accordion-template">
    <div class="accordion" id="mealtimes-accordion">
    </div>
</template>

<template id="mealtimes-accordion-item-template">
    <div id="mealtime-id-INSERT_MEALTIME_NUMBER" class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#mealtime-collapse-INSERT_MEALTIME_NUMBER">
                Mealtime name
            </button>
        </h2>
        <div id="mealtime-collapse-INSERT_MEALTIME_NUMBER" class="accordion-collapse collapse"
            data-bs-parent="#mealtimes-accordion">
            <div class="accordion-body">
            </div>
        </div>
    </div>
</template>

<template id="meals-list-template">
    <ul class="list-group list-group-flush">
    </ul>
</template>

<template id="meals-list-item-template">
    <button class="list-group-item" id="meal-id-INSERT_MEAL_ID">
        <h6 id="product-name">Product</h6><small class="text-body-secondary" id="meal-nutritional-info">Calories</small>
    </button>
</template>

<template id="meal-form-template">
    <form id="meal-form">
        <div class="container text-center">
            <div class="row justify-content-center">
                <div class="col-12 p-2">
                    <h3 id="food-name"></h3>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col p-2">
                    <table class="table" id="table-nutritional-values">
                        <thead>
                            <tr>
                                <th scope="col">kcal</th>
                                <th scope="col">fats</th>
                                <th scope="col">carbs</th>
                                <th scope="col">proteins</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-4 p-2">
                    <label for="meal-calories" class="form-label">Calories</label>
                </div>
                <div class="col-3 p-2">
                    <label for="meal-weight" class="form-label">Weight (g)</label>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-4 p-2">
                    <input type="text" id="meal-calories" class="form-control" placeholder="0 kcal" disabled>
                </div>
                <div class="col-3 p-2">
                    <input type="number" step="0.1" min="0" class="form-control" id="meal-weight">
                </div>
            </div>
            <div id="form-buttons" class="row justify-content-center">
                <div class="col-4 p-2">
                    <button type="submit" id="meal-add-button" class="btn btn-primary">Add meal</button>
                </div>
            </div>
        </div>
    </form>
</template>

<template id="daily-calories-template">
    <div class="container">
        <div class="row">
            <div class="col" id="daily-calories">
            </div>
        </div>
    </div>
</template>

<template id="product-form-template">
    <form id="product-form">
        <div class="container text-center">
            <div class="row justify-content-center">
                <div class="col-12 p-2">
                    <label for="product-name" class="form-label">Product name</label>
                    <input type="text" class="form-control" id="product-name">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col p-2">
                    <table class="table" id="table-nutritional-values">
                        <thead>
                            <tr>
                                <th colspan="4">Nutritional values per 100g</th>
                            </tr>
                            <tr>
                                <th scope="col">kcal</th>
                                <th scope="col">fats</th>
                                <th scope="col">carbs</th>
                                <th scope="col">proteins</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input type="number" step="0.1" min="0" class="form-control" id="product-calories">
                                </td>
                                <td><input type="number" step="0.1" min="0" class="form-control" id="product-fats"></td>
                                <td><input type="number" step="0.1" min="0" class="form-control" id="product-carbs">
                                </td>
                                <td><input type="number" step="0.1" min="0" class="form-control" id="product-proteins">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-8 p-2">
                    <label for="product-barcode" class="form-label">Barcode</label>
                </div>
                <div class="col-4 p-2">
                    <label for="product-portion-weight" class="form-label">Portion weight (g)</label>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-8 p-2">
                    <input type="text" id="product-barcode" class="form-control" min="0">
                </div>
                <div class="col-4 p-2">
                    <input type="number" step="0.1" min="0" class="form-control" id="product-portion-weight">
                </div>
            </div>
            <div id="form-buttons" class="row justify-content-center">
                <div class="col-5 p-2">
                    <button id="scan-product-button" class="btn btn-primary">Scan barcode</button>
                </div>
                <div class="col-4 p-2">
                    <button type="submit" id="product-form-submit-button" class="btn btn-primary"></button>
                </div>
            </div>
        </div>
    </form>
</template>

</html>

calorie_tracker/templates/calorie_tracker/meals.html
{% extends "calorie_tracker/layout.html" %}
{% load static %}
{% block content %}
<div id="meals-div">
</div>

<script>const csrftoken = "{{ csrf_token }}"</script>
<script src="{% static 'calorie_tracker/meals.js' %}"></script>
<script src="{% static 'calorie_tracker/products.js' %}"></script>
<script src="{% static 'calorie_tracker/scan.js' %}"></script>
{% endblock %}

calorie_tracker/templates/calorie_tracker/products.html
{% extends "calorie_tracker/layout.html" %}
{% load static %}
{% block content %}
<div id="react-content"></div>

<script>sessionStorage.setItem("csrftoken", "{{ csrf_token }}")</script>
<script src="{% static 'calorie_tracker/scan.js' %}"></script>
<script src="{% static 'calorie_tracker/react/pages/products.js' %}"></script>
{% endblock %}

calorie_tracker/templates/calorie_tracker/user.html
{% extends "calorie_tracker/layout.html" %}
{% load static %}
{% block content %}
<div id="react-content"></div>

<script> sessionStorage.setItem("current_user_id", "{{user_id}}");</script>
<script src="{% static 'calorie_tracker/react/pages/user.js' %}" type="application/javascript"></script>
{% endblock %}